version: '3.9'
services:
    webserver:
        container_name: webserver
        build:
            context: .
            dockerfile: ./docker-configs/nginx/Dockerfile
        ports:
            - 8081:80
        links:
            - core
        volumes_from:
            - data
        depends_on:
            - core

    core:
        container_name: core
        build:
            context: .
            dockerfile: ./docker-configs/php/Dockerfile
        env_file:
            - .env
        volumes:
            - ./docker-configs/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        volumes_from:
            - data
        depends_on:
            - mysql

    data:
        container_name: data
        build:
            context: .
            dockerfile: ./docker-configs/data/Dockerfile
        volumes:
            - /src
        command: chmod -R 0777 /src

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        command: mysqld --init-file="/etc/mysql/init/init.sql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password 
            MYSQL_DATABASE: kigadu
            MYSQL_USER: kigadu-admin
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
        volumes:
            - mysql:/var/lib/mysql
            - ./docker-configs/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker-configs/mysql/init.sql:/etc/mysql/init/init.sql

volumes:
    mysql:
        driver: local