columnSuffix: null
contentColumnType: string
fieldGroup: 45c467d8-6c9c-4ebb-8ede-0383a1a4d58e # Main
handle: mainPhoneSlider
instructions: 'There are the slide images of main phone slider'
name: 'Main Phone Slider'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:ea378c46-08de-4f28-a70f-b33e8717b63c' # Phone Slider Volume
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:ea378c46-08de-4f28-a70f-b33e8717b63c' # Phone Slider Volume
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:ea378c46-08de-4f28-a70f-b33e8717b63c' # Phone Slider Volume
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
