columnSuffix: null
contentColumnType: string
fieldGroup: 45c467d8-6c9c-4ebb-8ede-0383a1a4d58e # Main
handle: mainPhoneSliderAutoplay
instructions: 'On/Off autoplay and type the autoplay delay in seconds'
name: 'Main Phone Slider Autoplay'
searchable: false
settings:
  contentTable: '{{%matrixcontent_mainphonesliderautoplay}}'
  maxBlocks: 1
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
