columnSuffix: null
contentColumnType: string
fieldGroup: 45c467d8-6c9c-4ebb-8ede-0383a1a4d58e # Main
handle: mainText
instructions: 'Titile and Description at the first section'
name: 'Main Text'
searchable: false
settings:
  contentTable: '{{%matrixcontent_maintext}}'
  maxBlocks: 1
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
