defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  094ca1b0-0c84-48c1-aa7b-72b5ed5167af: # kigadu
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
